# Generated by Django 4.2.4 on 2024-01-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrecommend', '0006_remove_song_likes'),
        ('api', '0003_customuser_userlike_liked_on_alter_userlike_song_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='song',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserLike',
        ),
    ]
