# Generated by Django 4.2.4 on 2023-12-31 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicrecommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(related_name='liked_songs', through='api.UserLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
