# Generated by Django 4.2.4 on 2024-01-19 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userlike_song_alter_userlike_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicrecommend', '0002_song_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(related_name='song_likes', through='api.UserLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
