# Generated by Django 4.2.4 on 2024-01-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrecommend', '0003_alter_song_id_alter_song_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='id',
            new_name='song_id',
        ),
    ]
