# Generated by Django 4.2.4 on 2024-01-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrecommend', '0005_alter_song_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
